/**
 * App.tsx 전용 UI 문구 (다른 모듈과 중복되지 않는 항목).
 */
export const koApp = {
  errors: {
    passwordMismatch: "가문 비밀번호가 서로 일치하지 않습니다.",
    displayNameInvalid: "Player 1 같은 기본 이름 대신 사용할 가문 표시명을 입력하세요.",
    resetCodePrompt: "초기화 코드를 입력하세요.",
    checklistIncomplete: "회기 종료 전 확인 항목을 모두 체크하세요.",
  },
  header: {
    game: "게임 헤더",
  },
  sessionCheck: {
    section: "세션 확인",
    title: "의회 출입 기록을 확인 중입니다.",
    body: "잠시 후 현재 가문의 의회 화면 또는 가문 선택 화면으로 이동합니다.",
  },
  settings: {
    openSettings: "설정 열기",
    openTips: "팁 열기",
    dilemmaHistoryCount: (n: number) => `딜레마 이력 ${n}건`,
    secretScoreLink: "비밀 의제 점수",
    rulebookPdf: "룰북 PDF 보기",
    bgmUnmute: "BGM 음소거 해제",
    bgmMute: "BGM 음소거",
    bgmVolume: "BGM 음량",
    randomDiscardAria: (on: boolean) => `무작위 의제 폐기 ${on ? "ON" : "OFF"}`,
    randomDiscard: "무작위 의제 폐기",
    sharedSheet: "공유 시트 열기",
    voteOrderLocked: "현재 의제 선택 중에는 투표 순서를 바꿀 수 없습니다.",
    voteOrderHint: "투표 순서를 직접 조정합니다.",
    voteOrderNeedFive: "활성 가문 5명이 있어야 수정할 수 있습니다.",
    voteOrderButton: "투표 순서 설정",
    sessionEndReady: "이번 세션을 종료하고 체크리스트를 엽니다.",
    sessionEndPrep: "세션 종료 준비",
    leaveCouncil: "의회 퇴장",
    resetKingdom: "왕국 초기화",
  },
  brand: {
    title: "왕의 딜레마",
    subtitle: "가문 정보와 비밀 의제를 한 화면에서 관리합니다.",
  },
  login: {
    kingdomRound: "왕국 회기",
    pickHouseH2: "참여할 가문을 선택하세요",
    pickHouseBlurb:
      "이번 회의에 참여할 5개 가문을 고릅니다. 비밀 의제는 명망이 낮은 가문부터 선택합니다. 명망 동률에서는 가문 번호가 높은 쪽을 더 높은 명망으로 보므로, 낮은 번호 가문이 먼저 선택합니다.",
    houseExplain: "가문 설명",
    housePlaceholder: "가문을 선택하면 이곳에 해당 가문의 설명을 표시합니다.",
    rosterLabel: "가문 명부",
    pickHouseH3: "가문을 선택하세요",
    seatLegend: "가문 선택",
    countSuffix: "선택",
    absentFromMeeting: "회의 불참",
    notChosenYet: "아직 선택하지 않음",
    passwordHint: "가문을 고르면 표시명과 비밀번호를 기록합니다.",
    fieldPassword: "가문 비밀번호",
    fieldNewPassword: "새 가문 비밀번호",
    fieldPasswordConfirm: "가문 비밀번호 확인",
    fieldDisplayName: "가문 표시명",
    displayNamePlaceholder: "예: 올류드 후작가",
  },
  gamePanel: {
    statusTitle: "현황",
    councilProcedure: "의회 절차",
    myHouse: "내 가문",
    voteTurn: "투표 차례",
    turn: "차례",
    wait: "대기",
    currentPhase: "현재 단계",
    leader: "리더",
    moderator: "중재자",
    dilemma: "딜레마",
    housePick: "가문 선택",
    agendaPick: "의제 선택",
    draftAssistAria: "드래프트 보조 정보",
    beforeStart: "시작 전",
    privacyNote: "비밀 의제는 자기 차례가 오기 전까지 보이지 않습니다.",
    houseDetail: "가문 상세",
    narrativeGoal: "서사 목표",
    preferredAgenda: "선호 의제",
    alignmentSpan: "성향",
    alignmentTrackAria: "비밀 의제 성향별 달성 보상",
    crownRewardGroupAria: (label: string) => `${label} 왕관 보상`,
    crownTypeGroupAria: (label: string) => `${label} 왕관 종류`,
    crownCountAria: (label: string) => `${label} 왕관 개수`,
  },
  achievements: {
    challengeTooltip:
      "가문 화면의 업적은 조건을 만족할 때마다 칸 1개를 표시하고 모든 칸이 채워지면 능력이 해금됩니다. 서사 도전 과제는 특정 이야기 진행으로 열리는 장기 목표입니다.",
    alignmentTooltip:
      "가문 성향 업적은 매 게임 사용한 비밀 의제의 성향에 해당하는 칸을 1개 표시합니다. 모두 채우면 설정한 명망/갈망 보상을 반영합니다.",
  },
  inventory: {
    title: "가문",
    tokens: "토큰",
    victoryPoints: "승리 점수",
    detail: "상세",
    agendaTitle: "의제",
    agendaCommon: "공통",
    agendaSecret: "비밀",
    openScoreBtn: "공개 의제 점수",
    openScoreAria: "공개 의제 점수 산정 방식 자세히 보기",
    secretScoreBtn: "비밀 의제 점수",
    secretScoreAria: "비밀 의제 점수 산정 방식 자세히 보기",
    openAgendaAria: "공통 의제",
    secretAgendaAria: "비밀 의제",
    alignmentHeading: "업적",
    alignmentListAria: "성향 업적",
    ledgerSaveFail: "저장 실패",
    ledgerSaveOk: "저장 완료",
    ledgerSavingDesc: "변경사항을 의회 기록에 자동 저장하고 있습니다.",
    ledgerSavedDesc: "의회 기록에 자동 저장된 값입니다.",
    ledgerErrorDesc: "자동 저장에 실패했습니다. 연결이 복구되면 다시 시도합니다.",
    defaultsButton: "기본값",
    narrativeChallenge: "서사 도전 과제",
    challengeHeading: "도전 과제",
    achieveCancelAria: "서사 도전 과제 달성 취소",
    achieveSmall: "달성",
    achieveEditTooltip: "서사 도전 과제 조건과 효과 수정",
    achieveEditAria: "서사 도전 과제 조건과 효과 수정",
    conditionEffectEmpty: "조건/효과 미입력",
    challengeToggleAria: (label: string, done: boolean) => `${label} ${done ? "달성" : "미달성"}`,
    challengeCancelAria: (label: string) => `${label} 달성 취소`,
    challengeEditTooltip: (label: string) => `${label} 조건과 효과 수정`,
    challengeEditAria: (label: string) => `${label} 조건과 효과 수정`,
    alignmentAchievementAria: (label: string) => `${label} 성향 업적`,
    alignmentDecreaseAria: (label: string) => `${label} 성향 업적 줄이기`,
    alignmentCountAria: (label: string) => `${label} 성향 업적 표시 수`,
    alignmentIncreaseAria: (label: string) => `${label} 성향 업적 늘리기`,
    rewardFallback: "보상",
    rewardCrownsAria: (label: string, rewardLabel: string, count: number) => `${label} 보상 ${rewardLabel} ${count}개`,
    counterDecreaseAria: (label: string) => `${label} 내리기`,
    counterIncreaseAria: (label: string) => `${label} 올리기`,
    counterValueAria: (label: string) => `${label} 현재 값`,
    scoreTrackValueAria: (label: string) => `${label} 현재 값`,
    openAgendaTokenChipAria: (short: string, res: string) => `${short} ${res} 공개 의제 토큰`,
    photoSlotLimit: (n: number) => `사진은 최대 ${n}장까지 첨부할 수 있습니다.`,
    photoAttachFail: "사진을 첨부하지 못했습니다.",
    dilemmaResetConfirm: "현재 딜레마를 초기화할까요?",
    photoProcessing: "사진 처리 중입니다. 잠시 후 저장하세요.",
    achievementEditorTitleNarrative: "서사 도전 과제",
    achievementEditorTitleFallback: "도전 과제",
    headingHelpAria: (label: string) => `${label} 설명`,
  },
  gameStartConfirm: {
    title: "장부를 게임 시작 기본값으로 맞출까요?",
    header: "초기화:",
    coinsPower: (c: number, p: number) => `- 코인 ${c}, 권력 ${p}`,
    prestigeCrave: (pr: number, cr: number) => `- 명망 ${pr}, 갈망 ${cr}`,
    resources: (n: number, text: string) => `- 왕국 자원 ${n}종 ${text}`,
    openAgenda: (text: string) => `- 공개 의제: ${text}`,
    narrative: (cur: number, req: number) => `- 서사 도전 과제: ${cur}/${req}`,
    challenges: (text: string) => `- 도전 과제: ${text}`,
    alignAll: (n: number, m: number) => `- 선호 의제: ${n}개 모두 0/${m}`,
    rewardsNone: (n: number) => `- 달성 보상: ${n}개 모두 없음`,
    challengeRow: (label: string, cur: number, max: number) => `${label} ${cur}/${max}`,
    allSame: (count: number, max: number) => `${count}개 모두 0/${max}`,
    challengeLabelFallback: (i: number) => `도전 과제 ${i}`,
  },
  agendaUi: {
    visibleDiscardSection: "보이는 의제 폐기",
    pickVisibleDiscardTitle: "폐기할 의제 직접 선택",
    pickVisibleDiscardBody: "아래 목록에서 이번 드래프트에서 제외할 비밀 의제 1장을 고릅니다.",
    randomVisibleDiscardTitle: "보이는 의제 1장을 무작위 폐기",
    randomVisibleDiscardBody: "폐기할 의제는 공개하지 않습니다.",
    randomDiscardExecute: "무작위 폐기",
    agendasRemaining: (n: number) => `${n}장 남음`,
    discardOrDraft: (discard: boolean) => (discard ? "폐기" : "드래프트"),
    titleDiscard: "폐기할 비밀 의제 선택",
    titleDraft: "선택 가능한 비밀 의제",
    expand: (expanded: boolean) => (expanded ? "접기" : "자세히"),
    confirmDiscard: "이 비밀 의제를 폐기할까요? 폐기 후에는 되돌릴 수 없습니다.",
    confirmPick: "이 비밀 의제를 채택할까요? 채택 후에는 되돌릴 수 없습니다.",
    actionDiscard: "폐기",
    actionPick: "채택",
    resourceZonesTitle: "자원 구간",
    wealthRankTitle: "재화 순위",
    rankLabel: (r: string | number) => `${r}위`,
    scoreTitleDistance: "거리 산정",
    scoreTitleBoard: "보드 구간",
    zoneAria: "점수 구간",
    rowZoneAria: (row: number, active: boolean) => `${row}번 줄${active ? " 점수 구간" : ""}`,
    rowScoreAria: (label: string, vp: number) => `${label}: ${vp}점`,
    agendaScoreBoardAria: (agendaTitle: string) => `${agendaTitle} 점수 구간`,
    secretAgendaSection: "비밀 의제",
  },
} as const;
