/**
 * App.tsx 전용 UI 문구 (다른 모듈과 중복되지 않는 항목).
 */
export const koApp = {
  errors: {
    passwordMismatch: "가문 비밀번호가 서로 일치하지 않습니다.",
    displayNameInvalid: "Player 1 같은 기본 이름 대신 사용할 가문 표시명을 입력하세요.",
    resetCodePrompt: "초기화 코드를 입력하세요.",
    checklistIncomplete: "회기 종료 전 확인 항목을 모두 체크하세요.",
    sessionEndCauseRequired: "회기 종료 사유를 선택하세요.",
    sessionEndScoreRequired: "공용 보드 최종 위치를 모두 입력해 점수표를 계산하세요.",
  },
  header: {
    game: "게임 헤더",
  },
  sessionCheck: {
    section: "세션 확인",
    title: "의회 출입 기록을 확인 중입니다.",
    body: "잠시 후 현재 가문의 의회 화면 또는 가문 선택 화면으로 이동합니다.",
  },
  settings: {
    openSettings: "게임 메뉴 열기",
    openTips: "참고자료 열기",
    dilemmaHistoryCount: (n: number) => `딜레마 이력 ${n}건`,
    referencesSection: "참고자료",
    tipsCollectionTitle: "룰북 근거 팁 모음",
    tipsCollectionHint: "앱 곳곳의 보조 기능을 룰북 페이지 기준으로 빠르게 찾아봅니다.",
    gameFlowSection: "게임 흐름",
    physicalBoardSection: "기록",
    appSection: "앱 설정",
    secretScoreLink: "비밀 의제 점수",
    rulebookPdf: "룰북 PDF 보기",
    bgmUnmute: "BGM 음소거 해제",
    bgmMute: "BGM 음소거",
    bgmVolume: "BGM 음량",
    randomDiscardAria: (on: boolean) => `무작위 의제 폐기 ${on ? "ON" : "OFF"}`,
    randomDiscard: "무작위 의제 폐기",
    voteOrderLocked: "현재 의제 선택 중에는 투표 순서를 바꿀 수 없습니다.",
    voteOrderHint: "투표 순서를 직접 조정합니다.",
    voteOrderNeedFive: "활성 가문 5명이 있어야 수정할 수 있습니다.",
    voteOrderButton: "투표 순서 설정",
    sessionEndReady: "이번 세션을 종료하고 체크리스트를 엽니다.",
    sessionEndPrep: "세션 종료 준비",
    nextGameSetup: "다음 게임 준비",
    nextGameSetupHint: "연대기·레거시·공개 의제 배정을 룰북 순서로 확인합니다.",
    chronicleLedger: "연대기 장부",
    campaignLedger: "캠페인 장부",
    campaignBackfill: "기존 캠페인 가져오기",
    adminSection: "관리자",
    adminMode: "관리자 모드",
    adminModeAria: (on: boolean) => `관리자 모드 ${on ? "ON" : "OFF"}`,
    adminModeHint: "현재 가문 세션에 관리자 권한을 적용합니다.",
    adminModeTaken: (name: string) => `${name}이 관리자 모드를 사용 중입니다.`,
    kickHouse: (name: string) => `${name} 강퇴`,
    noActiveSessions: "활성 플레이어 세션이 없습니다.",
    leaveCouncil: "의회 퇴장",
    resetKingdom: "왕국 초기화",
  },
  brand: {
    title: "왕의 딜레마",
    subtitle: "가문 정보와 비밀 의제를 한 화면에서 관리합니다.",
  },
  login: {
    kingdomRound: "왕국 회기",
    pickHouseH2: "참여할 가문을 선택하세요",
    pickHouseBlurb:
      "이번 회의에 참여할 5개 가문을 고릅니다. 비밀 의제는 명망이 낮은 가문부터 선택합니다. 명망 동률에서는 가문 번호가 높은 쪽을 더 높은 명망으로 보므로, 낮은 번호 가문이 먼저 선택합니다.",
    houseExplain: "가문 설명",
    housePlaceholder: "가문을 선택하면 이곳에 해당 가문의 설명을 표시합니다.",
    rosterLabel: "가문 명부",
    pickHouseH3: "가문을 선택하세요",
    seatLegend: "가문 선택",
    countSuffix: "활성",
    absentFromMeeting: "회의 불참",
    notChosenYet: "아직 선택하지 않음",
    passwordHint: "가문을 고르면 표시명과 비밀번호를 기록합니다.",
    fieldPassword: "가문 비밀번호",
    fieldNewPassword: "새 가문 비밀번호",
    fieldPasswordConfirm: "가문 비밀번호 확인",
    fieldDisplayName: "가문 표시명",
    displayNamePlaceholder: "예: 올류드 후작가",
  },
  gamePanel: {
    statusTitle: "현황",
    councilProcedure: "의회 절차",
    myHouse: "내 가문",
    spectator: "관전 중",
    voteTurn: "투표 차례",
    turn: "차례",
    wait: "대기",
    currentPhase: "현재 단계",
    leader: "리더",
    moderator: "중재자",
    dilemma: "딜레마",
    housePick: "가문 선택",
    agendaPick: "의제 선택",
    draftAssistAria: "드래프트 보조 정보",
    beforeStart: "시작 전",
    privacyNote: "비밀 의제는 자기 차례가 오기 전까지 보이지 않습니다.",
    houseDetail: "가문 상세",
    narrativeGoal: "서사 목표",
    preferredAgenda: "선호 의제",
    alignmentSpan: "성향",
    alignmentTrackAria: "비밀 의제 성향별 달성 보상",
    crownRewardGroupAria: (label: string) => `${label} 왕관 보상`,
    crownTypeGroupAria: (label: string) => `${label} 왕관 종류`,
    crownCountAria: (label: string) => `${label} 왕관 개수`,
  },
  achievements: {
    challengeTooltip:
      "가문 화면의 업적은 조건을 만족할 때마다 칸 1개를 표시하고 모든 칸이 채워지면 능력이 해금됩니다. 서사 도전 과제는 특정 이야기 진행으로 열리는 장기 목표입니다.",
    alignmentTooltip:
      "가문 성향 업적은 매 게임 사용한 비밀 의제의 성향에 해당하는 칸을 1개 표시합니다. 모두 채우면 설정한 명망/갈망 보상을 반영합니다.",
  },
  inventory: {
    title: "가문",
    tokens: "토큰",
    victoryPoints: "승리 점수",
    detail: "상세",
    agendaTitle: "의제",
    agendaCommon: "공통",
    agendaSecret: "비밀",
    openScoreBtn: "공개 의제 점수",
    openScoreAria: "공개 의제 점수 산정 방식 자세히 보기",
    secretScoreBtn: "비밀 의제 점수",
    secretScoreAria: "비밀 의제 점수 산정 방식 자세히 보기",
    openAgendaAria: "공통 의제",
    secretAgendaAria: "비밀 의제",
    alignmentHeading: "업적",
    alignmentListAria: "성향 업적",
    ledgerSaveFail: "저장 실패",
    ledgerSaveOk: "저장 완료",
    ledgerSavingDesc: "변경사항을 의회 기록에 자동 저장하고 있습니다.",
    ledgerSavedDesc: "의회 기록에 자동 저장된 값입니다.",
    ledgerErrorDesc: "자동 저장에 실패했습니다. 연결이 복구되면 다시 시도합니다.",
    defaultsButton: "기본값",
    narrativeChallenge: "서사 도전 과제",
    challengeHeading: "도전 과제",
    achieveCancelAria: "서사 도전 과제 달성 취소",
    achieveSmall: "달성",
    achieveEditTooltip: "서사 도전 과제 조건과 효과 수정",
    achieveEditAria: "서사 도전 과제 조건과 효과 수정",
    conditionEffectEmpty: "조건/효과 미입력",
    challengeToggleAria: (label: string, done: boolean) => `${label} ${done ? "달성" : "미달성"}`,
    challengeCancelAria: (label: string) => `${label} 달성 취소`,
    challengeEditTooltip: (label: string) => `${label} 조건과 효과 수정`,
    challengeEditAria: (label: string) => `${label} 조건과 효과 수정`,
    alignmentAchievementAria: (label: string) => `${label} 성향 업적`,
    alignmentDecreaseAria: (label: string) => `${label} 성향 업적 줄이기`,
    alignmentCountAria: (label: string) => `${label} 성향 업적 표시 수`,
    alignmentIncreaseAria: (label: string) => `${label} 성향 업적 늘리기`,
    rewardFallback: "보상",
    rewardCrownsAria: (label: string, rewardLabel: string, count: number) => `${label} 보상 ${rewardLabel} ${count}개`,
    counterDecreaseAria: (label: string) => `${label} 내리기`,
    counterIncreaseAria: (label: string) => `${label} 올리기`,
    counterValueAria: (label: string) => `${label} 현재 값`,
    scoreTrackValueAria: (label: string) => `${label} 현재 값`,
    openAgendaTokenChipAria: (short: string, res: string) => `${short} ${res} 공개 의제 토큰`,
    photoSlotLimit: (n: number) => `사진은 최대 ${n}장까지 첨부할 수 있습니다.`,
    photoAttachFail: "사진을 첨부하지 못했습니다.",
    dilemmaResetConfirm: "현재 딜레마를 초기화할까요?",
    photoProcessing: "사진 처리 중입니다. 잠시 후 저장하세요.",
    achievementEditorTitleNarrative: "서사 도전 과제",
    achievementEditorTitleFallback: "도전 과제",
    headingHelpAria: (label: string) => `${label} 설명`,
  },
  nextGameSetup: {
    section: "다음 게임 준비",
    title: "셋업 · 레거시 · 공개 의제 보조",
    copy:
      "이 화면은 룰북 순서 확인과 장부 정리를 돕습니다. 공개 의제는 선택한 가문 수를 기준으로 2개 제한만 자동 검증합니다.",
    cleanupTitle: "최종 정리",
    defaultsTitle: "다음 게임 기본 셋업",
    legacyTitle: "레거시 처리",
    legacyResourceCopy:
      "연대기 장부의 현재 활성 스티커 기준입니다. 각 스티커를 한 칸 노화한 뒤, 긍정 스티커 수만큼 위로, 부정 스티커 수만큼 아래로 자원 레거시를 반영합니다. 안정도는 중앙에 두고 자원 마커 앞뒷면은 바꾸지 않습니다.",
    positiveChronicles: "긍정 연대기",
    negativeChronicles: "부정 연대기",
    legacyPositiveMove: (count: number) => `${count}개 · 위로 ${count}칸`,
    legacyNegativeMove: (count: number) => `${count}개 · 아래로 ${count}칸`,
    legacyNetMove: (net: number) => (net > 0 ? `위로 ${net}칸` : net < 0 ? `아래로 ${Math.abs(net)}칸` : "이동 없음"),
    openAgendaTitle: "공개 의제 배정 보조",
    openAgendaCopy:
      "연대기 장부는 참여 가문이 서명한 활성 스티커 중 가장 최근 스티커(노화 표시가 가장 적은 것, 동률이면 오른쪽)를 제안합니다. 필요하면 아래 선택값을 직접 고치세요.",
    suggestionsTitle: "장부 기반 제안",
    suggestionsCopy: "참여하지 않은 가문의 스티커는 무시합니다. 제안을 복사한 뒤 필요하면 수동 보정하세요.",
    suggestionsPreviewTitle: "제안 결과",
    copySuggestions: "제안을 선택값에 복사",
    suggestionsCopied: "공개 의제 제안을 선택값에 복사했습니다.",
    noSuggestedAssignments: "장부에서 배정할 공개 의제 제안이 없습니다.",
    unassigned: "미배정",
    warningTitle: "제한 확인",
    noWarnings: "현재 선택은 가문별 긍정 2개/부정 2개 제한 안에 있습니다.",
    applyAssignments: "수동 공개 의제 배정 저장",
    applyOk: "수동 공개 의제 배정을 저장했습니다.",
    applyFail: "수동 공개 의제 배정 저장에 실패했습니다.",
    checklistSaveOk: "체크리스트를 저장했습니다.",
    checklistSaveFail: "체크리스트 저장에 실패했습니다.",
    automationTitle: "셋업 자동화 적용",
    automationCopy:
      "연대기 노화, 자원 레거시 계산, 공개 의제 자동 배정을 서버에서 한 번에 적용합니다. 개인 코인·권력·업적·명망·갈망은 직접 관리하세요.",
    applyAutomation: "셋업 자동화 적용",
    automationApplyOk: "다음 게임 셋업 자동화를 적용했습니다.",
    automationApplyFail: "다음 게임 셋업 자동화 적용에 실패했습니다.",
    reapplyConfirm: (at: string, by: string) => `${at}에 ${by} 가문이 이미 적용했습니다. 연대기 노화가 다시 진행될 수 있습니다. 그래도 다시 적용할까요?`,
    lastAppliedTitle: "마지막 자동화 스냅샷",
    lastAppliedMeta: (at: string, by: string) => `${at} · 적용: ${by}`,
    lastLegacyTitle: "마지막 자원 레거시",
    lastLegacyNoMove: "마지막 자원 레거시 이동 없음",
    lastAssignmentsTitle: "마지막 공개 의제 배정",
    notAppliedYet: "아직 셋업 자동화 스냅샷이 없습니다.",
    unknownHouse: "알 수 없는",
    assignmentCount: (house: string, positive: number, negative: number) =>
      `${house}: 긍정 ${positive}/2 · 부정 ${negative}/2`,
    tooManyPositive: (house: string, count: number) => `${house} 가문의 긍정 공개 의제가 ${count}개입니다. 최대 2개만 보관합니다.`,
    tooManyNegative: (house: string, count: number) => `${house} 가문의 부정 공개 의제가 ${count}개입니다. 최대 2개만 보관합니다.`,
    checks: {
      cleanupTimeCounter: "시간 카운터의 해결된 딜레마 카드를 정리함",
      saveStoryEvents: "해금된 스토리·진행 중 이벤트 카드를 보관함",
      resetCards: "비밀 의제 카드와 투표 카드를 다음 게임 준비 위치로 돌림",
      defaultResources: "자원 마커를 중앙 행에 두고 방향을 무작위로 정함",
      defaultInventories: "각 가문 시작 코인/권력과 업적 보정을 확인함",
      leaderModerator: "최고 명망 리더, 최저 명망 중재자를 확인함",
      chronicleAging: "연대기 스티커를 한 칸 노화 처리함",
      legacyPower: "서명 연대기의 권력 레거시를 수기로 반영함",
      legacyResources: "자원 레거시는 안정도 이동 없이 수기로 반영함",
    } as Record<string, string>,
  },
  gameStartConfirm: {
    title: "장부를 게임 시작 기본값으로 맞출까요?",
    header: "초기화:",
    coinsPower: (c: number, p: number) => `- 코인 ${c}, 권력 ${p}`,
    prestigeCrave: (pr: number, cr: number) => `- 명망 ${pr}, 갈망 ${cr}`,
    resources: (n: number, text: string) => `- 왕국 자원 ${n}종 ${text}`,
    openAgenda: (text: string) => `- 공개 의제: ${text}`,
    narrative: (cur: number, req: number) => `- 서사 도전 과제: ${cur}/${req}`,
    challenges: (text: string) => `- 도전 과제: ${text}`,
    alignAll: (n: number, m: number) => `- 선호 의제: ${n}개 모두 0/${m}`,
    rewardsNone: (n: number) => `- 달성 보상: ${n}개 모두 없음`,
    challengeRow: (label: string, cur: number, max: number) => `${label} ${cur}/${max}`,
    allSame: (count: number, max: number) => `${count}개 모두 0/${max}`,
    challengeLabelFallback: (i: number) => `도전 과제 ${i}`,
  },
  agendaUi: {
    visibleDiscardSection: "보이는 의제 폐기",
    pickVisibleDiscardTitle: "폐기할 의제 직접 선택",
    pickVisibleDiscardBody: "아래 목록에서 이번 드래프트에서 제외할 비밀 의제 1장을 고릅니다.",
    randomVisibleDiscardTitle: "보이는 의제 1장을 무작위 폐기",
    randomVisibleDiscardBody: "폐기할 의제는 공개하지 않습니다.",
    randomDiscardExecute: "무작위 폐기",
    agendasRemaining: (n: number) => `${n}장 남음`,
    discardOrDraft: (discard: boolean) => (discard ? "폐기" : "드래프트"),
    titleDiscard: "폐기할 비밀 의제 선택",
    titleDraft: "선택 가능한 비밀 의제",
    expand: (expanded: boolean) => (expanded ? "접기" : "자세히"),
    confirmDiscard: "이 비밀 의제를 폐기할까요? 폐기 후에는 되돌릴 수 없습니다.",
    confirmPick: "이 비밀 의제를 채택할까요? 채택 후에는 되돌릴 수 없습니다.",
    actionDiscard: "폐기",
    actionPick: "채택",
    resourceZonesTitle: "자원 구간",
    wealthRankTitle: "재화 순위",
    rankLabel: (r: string | number) => `${r}위`,
    scoreTitleDistance: "거리 산정",
    scoreTitleBoard: "보드 구간",
    zoneAria: "점수 구간",
    rowZoneAria: (row: number, active: boolean) => `${row}번 줄${active ? " 점수 구간" : ""}`,
    rowScoreAria: (label: string, vp: number) => `${label}: ${vp}점`,
    agendaScoreBoardAria: (agendaTitle: string) => `${agendaTitle} 점수 구간`,
    secretAgendaSection: "비밀 의제",
  },
} as const;
