/**
 * 한글 UI 문자열 단일 원본. `gameResources`에서 `ko`로 재내보냅니다.
 */
export const ko = {
  common: {
    confirm: "확인",
    cancel: "취소",
    saving: "저장 중",
    save: "저장",
    delete: "삭제",
    close: "닫기",
    none: "없음",
    undecided: "미정",
    houseFallback: "가문",
    councilFallback: "의회",
    notSpecified: "미지정",
    noTitle: "제목 없음",
    powerTokenUnit: "권력",
    powerTokensLabel: "권력 토큰",
  },

  agenda: {
    requestFailed: "요청을 처리하지 못했습니다.",
  },

  carrot: {
    triggerAriaLabel: "보상 당근 흔들기",
    triggerLabel: "심심하면 당근이나 흔드세요.",
    comboFloating: (n: number) => `${n}x 콤보!`,
    boom: "💥 펑!",
    patternLabel: (name: string) => `패턴: ${name}`,
    gravityCenter: (x: string, y: string) => `중력 (${x}, ${y})`,
    freezeFloating: "❄️ 정지",
    unfreezeFloating: "🔥 정지 해제",
    helpTitle: "당근 단축키",
    frozenYes: "예",
    frozenNo: "아니오",
    shortcuts: [
      ["ESC", "전부 지우기·중지"],
      ["H", "도움말 켜기/끄기"],
      ["S", "통계 표시"],
      ["G", "중력 반전"],
      ["0", "무중력"],
      ["←↑→↓", "중력 기울이기"],
      ["F", "일시정지/해제"],
      ["SPACE", "한번에 소환 (×20)"],
      ["1-6", "소환 패턴"],
      ["Shift+드래그", "당근 끌어당기기"],
      ["Alt+드래그", "당근 밀어내기"],
      ["Ctrl+클릭", "중력 우물"],
      ["클릭 ×10", "펑!"],
    ] as const,
    stats: {
      fps: (n: number) => `FPS: ${n}`,
      carrots: (n: number) => `당근: ${n}`,
      particles: (n: number) => `가루: ${n}`,
      combo: (cur: number, best: number) => `콤보: ${cur} (최고: ${best})`,
      pattern: (s: string) => `패턴: ${s}`,
      gravity: (x: string, y: string) => `중력: (${x}, ${y})`,
      frozen: (on: boolean) => `정지: ${on ? "예" : "아니오"}`,
    },
  },

  dilemmaHistory: {
    confirmDelete: "선택한 딜레마 이력을 삭제할까요?",
    sectionCouncil: "의회 기록",
    title: "딜레마 이력",
    listAria: "저장된 딜레마 목록",
    empty: "저장된 딜레마 이력이 없습니다.",
    detailSection: "상세 기록",
    factCard: "카드",
    factSlot: "배치 위치",
    factResult: "결과",
    labelContext: "상황",
    labelQuestion: "질문",
    labelMemo: "메모",
    labelAye: "찬성",
    labelNay: "반대",
    labelVote: "투표",
    labelFollowUp: "후속",
    labelPhotosCard: "본문·보드 사진",
    labelPhotosResolution: "후속·결과 사진",
    labelResolutionChecklist: "해결 절차 체크",
    savedLine: (name: string, time: string) => `${name} 저장 — ${time}`,
  },

  sessionEnd: {
    sectionLabel: "회기 종료 확인",
    title: "다음 비밀 의제 드래프트 준비",
    copy:
      "공용 보드의 최종 위치를 기준으로 비밀 의제, 공개 의제, 코인 순위, 권력 보너스를 계산합니다. 회기 종료는 다음 비밀 의제 드래프트만 준비하며 코인/권력/공개 의제 표시는 자동으로 초기화하지 않습니다.",
    scoreSection: "점수 계산",
    boardTitle: "공용 보드 최종 위치",
    statusEnterPositions: "위치 입력",
    statusCalculating: "계산 중",
    statusDone: "계산 완료",
    statusWaiting: "계산 대기",
    boardFieldSuffix: "최종 위치",
    placeholderBoard: "1-17",
    scoreHintIncomplete: "5개 자원 위치를 모두 입력하면 점수표가 갱신됩니다.",
    scoreHintBusy: "점수 계산 중입니다.",
    scoreHintEmpty: "계산 결과를 기다리고 있습니다.",
    tableHouse: "가문",
    tableSecret: "비밀",
    tableOpen: "공개",
    tableCoin: "코인",
    tablePower: "권력",
    tableTotal: "합계",
    tableRank: "순위",
    rankSuffix: "위",
    endSession: "회기 종료",
  },

  specialLegend: {
    section: "업적 안내",
    title: "특수 능력 범례",
    imageAlt: "특수 능력 범례",
    caption: "특수 능력 범례",
    thGlyph: "표식",
    thTiming: "조건/표시",
    thEffect: "처리",
  },

  dilemmaHelpers: {
    breakdownEmpty: "없음",
    leaderVoteLine: (houseName: string, tokens: number) => `${houseName} ${tokens}권력`,
    ayeAdvantage: (d: number) => `찬성 우세 +${d}`,
    nayAdvantage: (d: number) => `반대 우세 +${d}`,
    tie: "동률",
    sideAye: "찬성",
    sideNay: "반대",
    sidePass: "기권",
    passCount: (n: number) => `${n}명`,
    powerTotal: (n: number) => `${n}권력`,
    defaultPhotoName: "딜레마사진",
    photoErrors: {
      imageOnly: "이미지 파일만 첨부할 수 있습니다.",
      maxSize: "사진 파일은 8MB 이하만 첨부할 수 있습니다.",
      tooLarge: "사진 용량이 큽니다. 더 작은 사진을 선택하세요.",
      processFail: "사진을 처리하지 못했습니다.",
      readFail: "사진을 읽지 못했습니다.",
      loadFail: "사진을 불러오지 못했습니다.",
    },
    publishNoRecord: "게시할 딜레마 기록이 없습니다.",
    publishNeedAllVotes: "로그인 중인 모든 가문이 투표해야 게시할 수 있습니다.",
    publishNeedOutcome: "딜레마 투표 결과를 직접 선택해야 게시할 수 있습니다.",
    publishNeedResolution: "후속 처리 내용을 입력해야 게시할 수 있습니다.",
    editingBy: (houseName: string) => `${houseName} 수정 중`,
    needRoles: "역할 지정 필요",
    needModerator: "중재자 지정 필요",
    needLeader: "리더 지정 필요",
    needWrite: "작성 필요",
    published: "게시 완료",
    votingNeeded: "투표 진행 필요",
    needOutcomePick: "결과 선택 필요",
    needFollowUp: "후속 입력 필요",
    canPublish: "게시 가능",
  },

  houseHelpers: {
    currentSeat: "현재 접속",
    agendaPickPhase: "의제 선택",
    houseChosen: "가문 선택됨",
    rosterFull: "정원 마감",
    canSelect: "선택 가능",
    dilemmaWrite: "딜레마 작성",
    outcomeDone: "결과 선택 완료",
    votingDone: "투표 완료",
    votingInProgress: "투표 진행 중",
    councilDilemmaBlurb:
      "리더와 중재자, 투표 방향, 투표 순서를 지정하고 이번 라운드의 딜레마를 작성하세요.",
    outcomeSelectedBlurb: "딜레마 투표 결과가 확정되었습니다. 후속 처리·게시를 진행하세요.",
    voteTurnForHouse: (name: string) => `${name} 가문의 투표 차례입니다.`,
    allVotedBlurb: "로그인 중인 모든 가문이 투표했습니다. 「집계 기록」으로 권력 합산을 확정하세요.",
    votingNegotiateBlurb:
      "자유 토론·협상 후 순서와 관계없이 투표·수정할 수 있습니다. 룰 요약: /king-dilemma-voting-rules.txt",
    moderatorTieBlurb: "찬성·반대 권력 합이 같습니다. 중재자만 결과(찬성/반대)를 확정할 수 있습니다.",
    councilUpdating: "의회 기록을 갱신하고 있습니다.",
    labelDilemmaOutcome: "딜레마 결과",
    labelDilemmaVote: "딜레마 투표",
    labelAgendaDiscard: "의제 폐기",
    labelSecretPick: "비밀 의제 선택",
    labelCouncilReady: "의회 준비",
    needAuthoring: "작성 필요",
    needOutcome: "결과 선택 필요",
    votingOngoing: "투표 진행",
  },

  mentionUi: {
    categoryEffect: "적용 시점",
    valueSelectTitle: "@ 값 선택",
    effectSelectTitle: "! 적용 시점 선택",
    noMatch: "일치하는 값이 없습니다.",
    reselect: "다시 선택",
    insert: "삽입",
    amountAria: "수치",
  },

  achievementUi: {
    noMemo: "효과 메모가 없습니다.",
    emptyEntry: "내용 미입력",
  },

  achievementEdit: {
    section: "가문 업적",
    titleEditSuffix: " 수정",
    legendAria: "특수 능력 범례",
    legendButton: "특수 능력 범례",
    conditionLabel: "조건 텍스트",
    conditionPlaceholder: "달성 조건을 입력합니다.",
    requiredCountLabel: "달성에 필요한 카운트",
    effectMemoLegend: "효과 메모",
    applyTimingLabel: "적용 시점",
    contentLabel: "내용",
    memoPlaceholder: "@코인 +2 또는 @명망 +1",
    removeMemoAria: (label: string) => `${label} 효과 메모 제거`,
    addMemo: "효과 메모 추가",
  },

  dilemmaRole: {
    saveOk: "리더와 중재자를 저장했습니다. 창을 닫습니다.",
    saveFail: "리더와 중재자를 저장하지 못했습니다.",
    section: "딜레마 준비",
    title: "리더·중재자 지정",
    voteOrderTooltip: "리더·중재자 지정 전 시계방향 좌석(룰북 §3 권장 발표 순서)을 확인합니다.",
    voteOrderButton: "투표 순서 지정",
    copy:
      "딜레마를 작성하기 전에 현재 리더 토큰 보유자와 중재자를 실제 테이블 상태에 맞춰 지정하세요. 투표 순서 설정은 별도의 시계방향 좌석 순서만 다룹니다.",
    leaderField: "리더 토큰",
    leaderPlaceholder: "리더 토큰 보유자 선택",
    leaderHint: "이번 딜레마 투표의 시작 기준입니다.",
    moderatorField: "중재자",
    moderatorPlaceholder: "중재자 선택",
    moderatorHint: "동률이나 전원 기권 때 결정권을 맡습니다.",
    noHouses: "로그인 중인 가문이 있을 때 리더와 중재자를 지정할 수 있습니다.",
    leaderTokenChip: "리더 토큰",
  },

  voteOrder: {
    saveOk: "투표 순서를 저장했습니다. 창을 닫습니다.",
    saveFail: "투표 순서를 저장하지 못했습니다.",
    dragUnknown: "알 수 없는 가문",
    dragMove: (house: string) => `${house} 좌석을 이동합니다.`,
    dragCanDrop: (house: string, pos: number) => `${house} ${pos}번째 위치에 놓을 수 있습니다.`,
    dragMoved: (house: string, pos: number) => `${house} ${pos}번째 위치로 이동했습니다.`,
    dragCancel: "순서 변경을 취소했습니다.",
    section: "의회 절차",
    title: "투표 순서 설정",
    copyP1:
      "실제 테이블의 시계방향 좌석 순서를 저장합니다. 룰북(King's Dilemma v35 §3 Vote of the Council)에서는 리더부터 시계방향으로 발표합니다. 이 앱에서는 협상·비동기 플레이를 위해 제출 순서를 막지 않으며, 순서 트랙은 권장 발표 차례만 표시합니다.",
    copyP2: "리더와 중재자는 투표 결과와 기권 선택을 마음대로 바꾸지 않습니다. 투표가 시작되면 순서를 바꿀 수 없습니다.",
    locked: "현재 딜레마 투표가 진행 중이라 순서를 수정할 수 없습니다.",
    keyboardHelp:
      "좌석을 드래그하거나 좌석에 초점을 둔 뒤 방향키로 한 칸씩 이동합니다. Home은 첫 번째 위치, End는 마지막 위치로 이동합니다.",
    orderSummaryAria: "현재 투표 순서",
    ringAria: "시계방향 투표 순서",
    needLogin: "로그인 중인 가문이 있을 때 순서를 설정할 수 있습니다.",
    seatAria: (n: number, house: string) => `${n}번째 ${house}`,
    seatKeyboardMoveAria: (n: number, displayName: string) => `${n}번째 ${displayName} 시계방향 순서 이동`,
  },

  dilemmaResolution: {
    sectionCouncil: "공용 기록",
    title: "딜레마 결과 · 후속 입력",
    stepTally: "1. 집계",
    tallyOk: "「집계 기록」으로 투표가 확정되었습니다. 룰북: 권력 합으로 다수를 정하고, 동률이면 중재자가 찬성/반대를 고릅니다.",
    tallyWait: "모든 가문이 투표한 뒤 의사 화면에서 「집계 기록」을 먼저 눌러 주세요.",
    powerCompare: (aye: number, nay: number) => `기록된 권력 합 — 찬성 ${aye} · 반대 ${nay}(기권은 합 비교에 포함되지 않습니다.)`,
    stepOutcome: "2. 결과",
    tieExplain: "찬성과 반대 권력 합이 같습니다. 중재자가 찬성 또는 반대 중 하나를 골라 확정합니다.",
    moderatorOnly: "중재자 가문만 여기서 동점을 확정할 수 있습니다.",
    outcomeLocked: (label: string) => `확정된 결과: 「${label}」`,
    outcomePending: "결과를 확정할 수 없습니다. 집계를 확인하거나 중재자 결정을 기다려 주세요.",
    stepFollowUp: "5. 후속 기록",
    followUpHint:
      "통과/기각에 따른 보드·스티커·자원 반영, 카드 처리 등 테이블 후속을 적습니다. 위의 룰북 절차 체크는 기록용입니다. (장부 수치는 별도로 저장합니다.)",
    phResolutionAfterTie: "동점이 해소된 뒤 입력합니다.",
    saveDisabledTie: "동점이 해소되어 결과가 정해진 뒤에 저장할 수 있습니다.",
    stepTimeSlot: "3. 시간 카운터 (룰북 E)",
    timeSlotHelp:
      "룰북 5장에 따라 승리한 쪽 결과를 반영한 뒤, 시간 트랙에 딜레마 카드를 둘 칸을 정하고 여기에 표기합니다.",
    labelTimeSlot: "트랙 칸 표기",
    phTimeSlot: "예: 시간 카운터 3",
    stepRulebookChecklist: "4. 룰북 해결 절차 (A–D, F)",
    rulebookChecklistHelp:
      "킹스 딜레마 룰북 5장「딜레마 해결」순서입니다. 테이블에서 확인한 항목을 표시합니다. 선택 사항이며 게시 조건과 별개입니다.",
    checklistItemA: "A. 승리한 쪽(찬성·반대) 카드 뒷면 결과를 읽음",
    checklistItemB: "B. 해당 결과에 따라 자원·안정도·추세 등 보드에 반영",
    checklistItemC: "C. 카드에 따라 연대기 스티커 부착",
    checklistItemD: "D. 카드에 따라 봉투 개봉",
    checklistItemF: "F. 라운드 종료 — 왕 확인(게임 종료 조건)",
    checklistMemoLabel: "연대기·봉투 등 메모(선택)",
    checklistMemoPh: "예: 연대기 ○○, 봉투 라벨",
    photoSectionTitle: "후속·결과 사진",
    photoHelp: "시간 카운터·보드 반영 등 후속 상태를 남기는 사진을 첨부합니다. Ctrl+V로 붙여넣을 수 있습니다.",
    photoAlt: "후속 사진",
    resultEntryButton: "결과",
    resultEntryTooltip: "집계 이후 확정된 결과, 시간 카운터, 후속 처리를 이 창에서만 기록합니다.",
    resultEntryTooltipLocked: "다른 가문이 딜레마를 편집 중이면 마칠 때까지 기다려 주세요.",
  },

  dilemmaEdit: {
    sharedSection: "공용 기록",
    photoSectionTitle: "사진",
    photoHelp: "보드게임 사진을 선택하거나 Ctrl+V로 붙여넣을 수 있습니다.",
    photoAttach: "사진 첨부",
    photoEmpty: "첨부된 사진이 없습니다.",
    photoLimitsCaption: (cur: number, max: number) =>
      `${cur}/${max} · 파일당 최대 8MB, 저장용 이미지는 자동 압축`,
    outcomeLegend: "선택 결과",
    outcomePickedBadge: "선택됨",
    resourceDeltaSection: "자원 변화",
    photoAlt: "딜레마 사진",
    undecidedTitle: "미정",
    noResultMeta: "결과 없음",
    ayeResultTitle: "찬성 결과",
    ayeResultMeta: "찬성 결과",
    nayResultTitle: "반대 결과",
    nayResultMeta: "반대 결과",
    unchanged: "변경 없음",
    waiting: "대기",
    titleNew: "딜레마 작성",
    titleEdit: "딜레마 편집",
    labelCardCode: "카드 번호",
    phCardCode: "예: 12, II-4",
    labelTitle: "제목",
    phTitle: "딜레마 제목",
    labelContext: "상황",
    phContext: "카드 전문 또는 요약이나 진행상황을 적습니다.",
    labelQuestion: "질문",
    phQuestion: "찬성/반대로 결정할 질문",
    labelMemo: "메모",
    phMemo: "회의 내용, 협상, 주의할 카드 효과",
    postVoteResolutionHint:
      "투표·집계 이후의 결과 확정, 시간 카운터, 「결과 후속」은 요약 카드의 「결과 입력」에서만 기록합니다.",
    outcomeDisabled: "로그인 중인 모든 가문이 투표해야 결과를 선택할 수 있습니다.",
    labelAye: "찬성",
    labelNay: "반대",
    labelResolution: "결과 후속",
    phResolutionLocked: "전원 투표 후 입력할 수 있습니다.",
    phResolution: "자원/안정도/모멘텀, 스티커, 보드 투입, 카드 처리",
    saving: "저장",
    labelSummary: "요약",
    phSummary: "투표지에 적을 간단한 결과",
    labelOutcomeShort: "결과",
    phOutcome: "의제 통과 후 처리 내용",
  },

  mysteryStickers: {
    none: "선택 안 함",
    sectionTitle: "이야기 카드 칸",
    ariaGroup: "이야기 카드 칸 선택",
    currentBadge: "적용 중",
    previewLabel: "배치",
    previewAlt: "선택한 이야기 카드 칸",
    placement1: "배치 1",
    placement2: "배치 2",
    placement3: "배치 3",
    placement4: "배치 4",
    placement5: "배치 5",
    placement6: "배치 6",
    missingFileHint: (slot: number) => `${slot}번 배치 아이콘을 불러오지 못했습니다.`,
    missingFileHintUnknown: "배치 아이콘을 불러오지 못했습니다.",
  },

  dilemmaUi: {
    factAdvantage: "우세",
    outcomeSelectedChip: "선택",
    outcomeEmptyPreview: "결과 미입력",
    roleTooltipLocked: "딜레마 편집을 저장하거나 취소해야 역할을 지정할 수 있습니다.",
    roleTooltipWrongPhase: "딜레마 작성 전 상태에서만 역할을 지정할 수 있습니다.",
    roleTooltipOk: "딜레마 작성 전에 리더 토큰과 중재자를 지정합니다.",
    editTooltipWait: "다른 가문이 편집을 마칠 때까지 기다려야 합니다.",
    editTooltipNeedRoles: "리더와 중재자를 먼저 지정하세요.",
    editTooltipNew: "새 딜레마를 작성합니다.",
    editTooltipEdit: "딜레마 기록을 편집합니다.",
    publishTooltipLocked: "딜레마 편집을 저장하거나 취소해야 게시할 수 있습니다.",
    publishTooltipEmpty: "게시할 딜레마 기록이 없습니다.",
    publishTooltipDefault: "현재 저장된 딜레마를 딜레마 이력에 게시합니다.",
    publishTooltipAuthorOnly: "딜레마를 처음 작성한 가문만 게시할 수 있습니다.",
    resetTooltipWait: "다른 가문이 편집을 마칠 때까지 초기화할 수 없습니다.",
    resetTooltipNone: "초기화할 딜레마 기록이나 역할이 없습니다.",
    resetTooltipAuthorOnly: "딜레마를 처음 작성한 가문만 결과를 초기화할 수 있습니다.",
    resetTooltipOk: "현재 딜레마 기록과 리더/중재자를 초기화합니다. 게시된 이력은 유지됩니다.",
    ledgerTitle: "딜레마",
    roleButton: "역할",
    write: "작성",
    edit: "편집",
    reset: "초기화",
    publish: "게시",
    emptyRound: "이번 라운드의 딜레마 기록이 아직 없습니다.",
    photoStripAria: "딜레마사진",
    photoStripResolutionAria: "딜레마 후속 사진",
    summaryLabelCardCode: "카드 번호",
    summaryLabelTitle: "제목",
    summaryLabelTimeSlot: "시간 카운터",
    summaryLabelStorySticker: "이야기 칸",
    savedLine: (name: string, time: string) => `${name} 저장 — ${time}`,
    voteBreakdownAria: "딜레마 투표 결과 상세",
    resourceDeltaAria: "자원 변화",
    breakdownEmpty: "없음",
    powerEm: (n: number) => `${n}권력`,
    sessionLeader: "리더",
    sessionModerator: "중재자",
    turnTrackAria: "의회 차례",
    currentTurn: "현재 차례",
    agendaChosen: "의제 선택 완료",
    voteOrderAria: "딜레마 투표 순서",
    nthHouse: (n: number, label: string) => `${n}번째 ${label}`,
    legendLeader: "리더",
    legendModerator: "중재자",
    legendCurrent: "권장 차례(테이블)",
    houseSelectRemain: (n: number) =>
      `${n}개 가문이 더 선택하면 명망이 낮은 가문부터 비밀 의제 드래프트를 시작합니다. 명망 동률에서는 가문 번호가 높은 쪽이 더 높은 명망이므로 낮은 번호가 먼저입니다.`,
    seatsFull: "좌석이 모두 찼습니다. 첫 가문이 의제 폐기를 시작합니다.",
    outcomePickedBlurb: (label: string) =>
      `${label} 결과가 선택되었습니다. 딜레마 후속 처리를 기록하세요.`,
    myVoteTurn:
      "투표할 수 있습니다. 찬성·반대·기권 중 하나를 고르세요. 테이블에서는 리더부터 시계 방향이 권장될 뿐, 앱에서는 순서와 관계없이 제출·수정할 수 있습니다.",
    voteTurnLine: (name: string) => `테이블 권장 발표 순서: ${name} 가문`,
    allVotedRecord:
      "모든 가문이 투표했습니다. 「집계 기록」을 누르면 권력 다수가 결과에 반영되고, 동률이면 중재자가 결과를 고릅니다.",
    needRolesWrite: "리더 토큰 보유자와 중재자를 지정한 뒤 이번 라운드의 딜레마를 작성하세요.",
    discardRandom: (name: string) =>
      `${name} 차례입니다. 보이는 6장 중 1장을 무작위로 폐기하고 남은 의제를 받습니다.`,
    discardPick: (name: string) =>
      `${name} 차례입니다. 보이는 6장 중 폐기할 의제 1장을 직접 고르세요.`,
    chooseSecret: (name: string) => `${name} 차례입니다. 남은 비밀 의제 중 하나를 고르세요.`,
    choiceDone: "선택 완료. 다른 가문의 차례에는 남은 의제가 보이지 않습니다.",
    waitingTurn: (self: string, turn: string) =>
      `${self} 대기 중. 지금은 ${turn} 차례이며 남은 의제가 보이지 않습니다.`,
    voteSavedOk: "투표를 저장했습니다.",
    voteSavedFail: "투표를 저장하지 못했습니다.",
    applyOk: "투표를 집계했습니다. 권력 다수에 따라 결과가 반영되었거나, 동률이면 중재자 결정 단계입니다.",
    applyHint:
      "모든 가문이 투표하면 「집계 기록」으로 확정합니다. 다수 권력이 결과를 정하고, 동률이면 중재자가 고릅니다.",
    applyWaitEditor:
      "모든 가문이 투표했습니다. 딜레마 본문을 저장한 가문만 「집계 기록」을 누를 수 있습니다.",
    applyFail: "투표 집계를 기록하지 못했습니다.",
    voteSummaryOutcome: (label: string) => `${label} 선택됨`,
    votePhaseProgress: "투표 진행",
    votePhaseComplete: "투표 완료",
    tallyLine: (aye: number, nay: number, pass: number) => `찬성 ${aye} · 반대 ${nay} · 기권 ${pass}`,
    allHouseVotedLine: "참여 중인 모든 가문이 투표했습니다.",
    turnOnly: (name: string) => `테이블 권장: ${name}`,
    voteCountLine: (done: number, total: number) => `${done}/${total || 0} 투표`,
    voteRoleGridAria: "투표 역할과 선두",
    leaderShort: "리더",
    moderatorShort: "중재자",
    ayeLead: "찬성 선두",
    nayLead: "반대 선두",
    advantageNow: "현재 우세",
    waitYourTurn: "지금 이 화면에서 투표를 바꿀 수 없습니다. 집계가 확정됐거나 이미 제출했을 수 있습니다.",
    voteSubmittedWaitOthers: "투표를 제출했습니다. 다른 가문의 제출을 기다립니다.",
    voteOptionsAria: "딜레마투표 선택",
    stepperMinusAria: "권력 토큰 줄이기",
    stepperPlusAria: "권력 토큰 늘리기",
    wagerOutputAria: "투표에 거는 권력 토큰",
    saveVote: "투표 저장",
    moderatorDecideAria: "동점 시 중재자 결정",
    moderatorPickAye: "동점 — 찬성으로 확정",
    moderatorPickNay: "동점 — 반대로 확정",
    applyTally: "집계 기록",
    moderatorResolveOk: "중재자 결정을 반영했습니다.",
    moderatorResolveFail: "중재자 결정을 반영하지 못했습니다.",
    labelAye: "찬성",
    labelNay: "반대",
    labelPass: "기권",
  },

};

export type Ko = typeof ko;
