/**
 * 한글 UI 문자열 단일 원본. `gameResources`에서 `ko`로 재내보냅니다.
 */
export const ko = {
  common: {
    confirm: "확인",
    cancel: "취소",
    saving: "저장 중",
    save: "저장",
    delete: "삭제",
    close: "닫기",
    none: "없음",
    undecided: "미정",
    houseFallback: "가문",
    councilFallback: "의회",
    notSpecified: "미지정",
    noTitle: "제목 없음",
    powerTokenUnit: "권력",
    powerTokensLabel: "권력 토큰",
  },

  agenda: {
    requestFailed: "요청을 처리하지 못했습니다.",
  },

  carrot: {
    triggerAriaLabel: "보상 당근 흔들기",
    triggerLabel: "심심하면 당근이나 흔드세요.",
    comboFloating: (n: number) => `${n}x 콤보!`,
    boom: "💥 펑!",
    patternLabel: (name: string) => `패턴: ${name}`,
    gravityCenter: (x: string, y: string) => `중력 (${x}, ${y})`,
    freezeFloating: "❄️ 정지",
    unfreezeFloating: "🔥 정지 해제",
    helpTitle: "당근 단축키",
    frozenYes: "예",
    frozenNo: "아니오",
    shortcuts: [
      ["ESC", "전부 지우기·중지"],
      ["H", "도움말 켜기/끄기"],
      ["S", "통계 표시"],
      ["G", "중력 반전"],
      ["0", "무중력"],
      ["←↑→↓", "중력 기울이기"],
      ["F", "일시정지/해제"],
      ["SPACE", "한번에 소환 (×20)"],
      ["1-6", "소환 패턴"],
      ["Shift+드래그", "당근 끌어당기기"],
      ["Alt+드래그", "당근 밀어내기"],
      ["Ctrl+클릭", "중력 우물"],
      ["클릭 ×10", "펑!"],
    ] as const,
    stats: {
      fps: (n: number) => `FPS: ${n}`,
      carrots: (n: number) => `당근: ${n}`,
      particles: (n: number) => `가루: ${n}`,
      combo: (cur: number, best: number) => `콤보: ${cur} (최고: ${best})`,
      pattern: (s: string) => `패턴: ${s}`,
      gravity: (x: string, y: string) => `중력: (${x}, ${y})`,
      frozen: (on: boolean) => `정지: ${on ? "예" : "아니오"}`,
    },
  },

  dilemmaHistory: {
    confirmDelete: "선택한 딜레마 이력을 삭제할까요?",
    sectionCouncil: "의회 기록",
    title: "딜레마 이력",
    listAria: "저장된 딜레마 목록",
    empty: "저장된 딜레마 이력이 없습니다.",
    detailSection: "상세 기록",
    factCard: "카드",
    factSlot: "배치 위치",
    factResult: "결과",
    labelContext: "상황",
    labelQuestion: "질문",
    labelMemo: "메모",
    labelAye: "찬성",
    labelNay: "반대",
    labelVote: "투표",
    labelFollowUp: "후속",
    savedLine: (name: string, time: string) => `${name} 저장 · ${time}`,
  },

  sessionEnd: {
    sectionLabel: "회기 종료 확인",
    title: "다음 비밀 의제 드래프트 준비",
    copy:
      "공용 보드의 최종 위치를 기준으로 비밀 의제, 공개 의제, 코인 순위, 권력 보너스를 계산합니다. 회기 종료는 다음 비밀 의제 드래프트만 준비하며 코인/권력/공개 의제 표시는 자동으로 초기화하지 않습니다.",
    scoreSection: "점수 계산",
    boardTitle: "공용 보드 최종 위치",
    statusEnterPositions: "위치 입력",
    statusCalculating: "계산 중",
    statusDone: "계산 완료",
    statusWaiting: "계산 대기",
    boardFieldSuffix: "최종 위치",
    placeholderBoard: "1-17",
    scoreHintIncomplete: "5개 자원 위치를 모두 입력하면 점수표가 갱신됩니다.",
    scoreHintBusy: "점수 계산 중입니다.",
    scoreHintEmpty: "계산 결과를 기다리고 있습니다.",
    tableHouse: "가문",
    tableSecret: "비밀",
    tableOpen: "공개",
    tableCoin: "코인",
    tablePower: "권력",
    tableTotal: "합계",
    tableRank: "순위",
    rankSuffix: "위",
    endSession: "회기 종료",
  },

  specialLegend: {
    section: "업적 안내",
    title: "특수 능력 범례",
    imageAlt: "특수 능력 범례",
    caption: "특수 능력 범례",
    thGlyph: "표식",
    thTiming: "조건/표시",
    thEffect: "처리",
  },

  dilemmaHelpers: {
    breakdownEmpty: "없음",
    leaderVoteLine: (houseName: string, tokens: number) => `${houseName} ${tokens}권력`,
    ayeAdvantage: (d: number) => `찬성 우세 +${d}`,
    nayAdvantage: (d: number) => `반대 우세 +${d}`,
    tie: "동률",
    sideAye: "찬성",
    sideNay: "반대",
    sidePass: "기권",
    passCount: (n: number) => `${n}명`,
    powerTotal: (n: number) => `${n}권력`,
    defaultPhotoName: "딜레마사진",
    photoErrors: {
      imageOnly: "이미지 파일만 첨부할 수 있습니다.",
      maxSize: "사진 파일은 8MB 이하만 첨부할 수 있습니다.",
      tooLarge: "사진 용량이 큽니다. 더 작은 사진을 선택하세요.",
      processFail: "사진을 처리하지 못했습니다.",
      readFail: "사진을 읽지 못했습니다.",
      loadFail: "사진을 불러오지 못했습니다.",
    },
    publishNoRecord: "게시할 딜레마 기록이 없습니다.",
    publishNeedAllVotes: "로그인 중인 모든 가문이 투표해야 게시할 수 있습니다.",
    publishNeedOutcome: "딜레마 투표 결과를 직접 선택해야 게시할 수 있습니다.",
    publishNeedResolution: "후속 처리 내용을 입력해야 게시할 수 있습니다.",
    editingBy: (houseName: string) => `${houseName} 수정 중`,
    needRoles: "역할 지정 필요",
    needModerator: "중재자 지정 필요",
    needLeader: "리더 지정 필요",
    needWrite: "작성 필요",
    published: "게시 완료",
    votingNeeded: "투표 진행 필요",
    needOutcomePick: "결과 선택 필요",
    needFollowUp: "후속 입력 필요",
    canPublish: "게시 가능",
  },

  houseHelpers: {
    currentSeat: "현재 접속",
    agendaPickPhase: "의제 선택",
    houseChosen: "가문 선택됨",
    rosterFull: "정원 마감",
    canSelect: "선택 가능",
    dilemmaWrite: "딜레마 작성",
    outcomeDone: "결과 선택 완료",
    votingDone: "투표 완료",
    votingInProgress: "투표 진행 중",
    councilDilemmaBlurb:
      "리더와 중재자, 투표 방향, 투표 순서를 지정하고 이번 라운드의 딜레마를 작성하세요.",
    outcomeSelectedBlurb: "딜레마 투표 결과가 선택되었습니다. 후속 처리를 수기로 기록하고 게시하세요.",
    voteTurnForHouse: (name: string) => `${name} 가문의 투표 차례입니다.`,
    allVotedBlurb: "로그인 중인 모든 가문이 투표했습니다. 결과와 후속 처리를 직접 기록하세요.",
    councilUpdating: "의회 기록을 갱신하고 있습니다.",
    labelDilemmaOutcome: "딜레마 결과",
    labelDilemmaVote: "딜레마 투표",
    labelAgendaDiscard: "의제 폐기",
    labelSecretPick: "비밀 의제 선택",
    labelCouncilReady: "의회 준비",
    needAuthoring: "작성 필요",
    needOutcome: "결과 선택 필요",
    votingOngoing: "투표 진행",
  },

  mentionUi: {
    categoryEffect: "적용 시점",
    valueSelectTitle: "@ 값 선택",
    effectSelectTitle: "! 적용 시점 선택",
    noMatch: "일치하는 값이 없습니다.",
    reselect: "다시 선택",
    insert: "삽입",
    amountAria: "수치",
  },

  achievementUi: {
    noMemo: "효과 메모가 없습니다.",
    emptyEntry: "내용 미입력",
  },

  achievementEdit: {
    section: "가문 업적",
    titleEditSuffix: " 수정",
    legendAria: "특수 능력 범례",
    legendButton: "특수 능력 범례",
    conditionLabel: "조건 텍스트",
    conditionPlaceholder: "달성 조건을 입력합니다.",
    requiredCountLabel: "달성에 필요한 카운트",
    effectMemoLegend: "효과 메모",
    applyTimingLabel: "적용 시점",
    contentLabel: "내용",
    memoPlaceholder: "@코인 +2 또는 @명망 +1",
    removeMemoAria: (label: string) => `${label} 효과 메모 제거`,
    addMemo: "효과 메모 추가",
  },

  dilemmaRole: {
    saveOk: "리더와 중재자를 저장했습니다. 창을 닫습니다.",
    saveFail: "리더와 중재자를 저장하지 못했습니다.",
    section: "딜레마 준비",
    title: "리더·중재자 지정",
    voteOrderTooltip: "리더와 중재자 지정 전에 시계방향 투표 순서를 확인합니다.",
    voteOrderButton: "투표 순서 지정",
    copy:
      "딜레마를 작성하기 전에 현재 리더 토큰 보유자와 중재자를 실제 테이블 상태에 맞춰 지정하세요. 투표 순서 설정은 별도의 시계방향 좌석 순서만 다룹니다.",
    leaderField: "리더 토큰",
    leaderPlaceholder: "리더 토큰 보유자 선택",
    leaderHint: "이번 딜레마 투표의 시작 기준입니다.",
    moderatorField: "중재자",
    moderatorPlaceholder: "중재자 선택",
    moderatorHint: "동률이나 전원 기권 때 결정권을 맡습니다.",
    noHouses: "로그인 중인 가문이 있을 때 리더와 중재자를 지정할 수 있습니다.",
    leaderTokenChip: "리더 토큰",
  },

  voteOrder: {
    saveOk: "투표 순서를 저장했습니다. 창을 닫습니다.",
    saveFail: "투표 순서를 저장하지 못했습니다.",
    dragUnknown: "알 수 없는 가문",
    dragMove: (house: string) => `${house} 좌석을 이동합니다.`,
    dragCanDrop: (house: string, pos: number) => `${house} ${pos}번째 위치에 놓을 수 있습니다.`,
    dragMoved: (house: string, pos: number) => `${house} ${pos}번째 위치로 이동했습니다.`,
    dragCancel: "순서 변경을 취소했습니다.",
    section: "의회 절차",
    title: "투표 순서 설정",
    copyP1:
      "이 화면의 좌석은 실제 참석 기준의 시계방향 순서만 저장합니다. 딜레마 투표는 현재 리더 토큰 보유자의 위치에서 시작해 이 순서를 따라 진행합니다.",
    copyP2: "리더와 중재자는 투표 결과와 기권 선택을 마음대로 바꾸지 않습니다. 투표가 시작되면 순서를 바꿀 수 없습니다.",
    locked: "현재 딜레마 투표가 진행 중이라 순서를 수정할 수 없습니다.",
    keyboardHelp:
      "좌석을 드래그하거나 좌석에 초점을 둔 뒤 방향키로 한 칸씩 이동합니다. Home은 첫 번째 위치, End는 마지막 위치로 이동합니다.",
    orderSummaryAria: "현재 투표 순서",
    ringAria: "시계방향 투표 순서",
    needLogin: "로그인 중인 가문이 있을 때 순서를 설정할 수 있습니다.",
    seatAria: (n: number, house: string) => `${n}번째 ${house}`,
    seatKeyboardMoveAria: (n: number, displayName: string) => `${n}번째 ${displayName} 시계방향 순서 이동`,
  },

  dilemmaEdit: {
    sharedSection: "공용 기록",
    photoSectionTitle: "사진",
    photoHelp: "보드게임 사진을 선택하거나 Ctrl+V로 붙여넣을 수 있습니다.",
    photoAttach: "사진 첨부",
    photoEmpty: "첨부된 사진이 없습니다.",
    photoLimitsCaption: (cur: number, max: number) =>
      `${cur}/${max} · 파일당 최대 8MB, 저장용 이미지는 자동 압축`,
    outcomeLegend: "선택 결과",
    outcomePickedBadge: "선택됨",
    resourceDeltaSection: "자원 변화",
    photoAlt: "딜레마 사진",
    undecidedTitle: "미정",
    noResultMeta: "결과 없음",
    ayeResultTitle: "찬성 결과",
    ayeResultMeta: "찬성 결과",
    nayResultTitle: "반대 결과",
    nayResultMeta: "반대 결과",
    unchanged: "변경 없음",
    waiting: "대기",
    titleNew: "딜레마 작성",
    titleEdit: "딜레마 편집",
    labelCardCode: "카드 번호",
    phCardCode: "예: 12, II-4",
    labelTitle: "제목",
    phTitle: "딜레마 제목",
    labelSlot: "카드 배치 위치",
    phSlot: "예: 시간 칸 3",
    labelContext: "상황",
    phContext: "카드 전문 또는 요약이나 진행상황을 적습니다.",
    labelQuestion: "질문",
    phQuestion: "찬성/반대로 결정할 질문",
    labelMemo: "메모",
    phMemo: "회의 내용, 협상, 주의할 카드 효과",
    outcomeDisabled: "로그인 중인 모든 가문이 투표해야 결과를 선택할 수 있습니다.",
    labelAye: "찬성",
    labelNay: "반대",
    labelResolution: "결과 후속",
    phResolutionLocked: "전원 투표 후 입력할 수 있습니다.",
    phResolution: "자원/안정도/모멘텀, 스티커, 보드 투입, 카드 처리",
    saving: "저장",
    labelSummary: "요약",
    phSummary: "투표지에 적을 간단한 결과",
    labelOutcomeShort: "결과",
    phOutcome: "의제 통과 후 처리 내용",
  },

  dilemmaUi: {
    factAdvantage: "우세",
    outcomeSelectedChip: "선택",
    outcomeEmptyPreview: "결과 미입력",
    roleTooltipLocked: "딜레마 편집을 저장하거나 취소해야 역할을 지정할 수 있습니다.",
    roleTooltipWrongPhase: "딜레마 작성 전 상태에서만 역할을 지정할 수 있습니다.",
    roleTooltipOk: "딜레마 작성 전에 리더 토큰과 중재자를 지정합니다.",
    editTooltipWait: "다른 가문이 편집을 마칠 때까지 기다려야 합니다.",
    editTooltipNeedRoles: "리더와 중재자를 먼저 지정하세요.",
    editTooltipNew: "새 딜레마를 작성합니다.",
    editTooltipEdit: "딜레마 기록을 편집합니다.",
    publishTooltipLocked: "딜레마 편집을 저장하거나 취소해야 게시할 수 있습니다.",
    publishTooltipEmpty: "게시할 딜레마 기록이 없습니다.",
    publishTooltipDefault: "현재 저장된 딜레마를 딜레마 이력에 게시합니다.",
    resetTooltipWait: "다른 가문이 편집을 마칠 때까지 초기화할 수 없습니다.",
    resetTooltipNone: "초기화할 딜레마 기록이나 역할이 없습니다.",
    resetTooltipOk: "현재 딜레마 기록과 리더/중재자를 초기화합니다. 게시된 이력은 유지됩니다.",
    ledgerTitle: "딜레마",
    roleButton: "역할",
    write: "작성",
    edit: "편집",
    reset: "초기화",
    publish: "게시",
    emptyRound: "이번 라운드의 딜레마 기록이 아직 없습니다.",
    photoStripAria: "딜레마사진",
    savedLine: (name: string, time: string) => `${name} 저장 · ${time}`,
    voteBreakdownAria: "딜레마 투표 결과 상세",
    resourceDeltaAria: "자원 변화",
    breakdownEmpty: "없음",
    powerEm: (n: number) => `${n}권력`,
    sessionLeader: "리더",
    sessionModerator: "중재자",
    turnTrackAria: "의회 차례",
    currentTurn: "현재 차례",
    agendaChosen: "의제 선택 완료",
    voteOrderAria: "딜레마 투표 순서",
    nthHouse: (n: number, label: string) => `${n}번째 ${label}`,
    legendLeader: "리더",
    legendModerator: "중재자",
    legendCurrent: "현재 차례",
    houseSelectRemain: (n: number) =>
      `${n}개 가문이 더 선택하면 명망이 낮은 가문부터 비밀 의제 드래프트를 시작합니다. 명망 동률에서는 가문 번호가 높은 쪽이 더 높은 명망이므로 낮은 번호가 먼저입니다.`,
    seatsFull: "좌석이 모두 찼습니다. 첫 가문이 의제 폐기를 시작합니다.",
    outcomePickedBlurb: (label: string) =>
      `${label} 결과가 선택되었습니다. 딜레마 후속 처리를 수기로 기록하세요.`,
    myVoteTurn: "내 투표 차례입니다. 찬성, 반대, 기권 중 하나를 선택하세요.",
    voteTurnLine: (name: string) => `${name} 가문의 투표 차례입니다.`,
    allVotedRecord: "로그인 중인 모든 가문이 투표했습니다. 결과와 후속 처리를 직접 기록하세요.",
    needRolesWrite: "리더 토큰 보유자와 중재자를 지정한 뒤 이번 라운드의 딜레마를 작성하세요.",
    discardRandom: (name: string) =>
      `${name} 차례입니다. 보이는 6장 중 1장을 무작위로 폐기하고 남은 의제를 받습니다.`,
    discardPick: (name: string) =>
      `${name} 차례입니다. 보이는 6장 중 폐기할 의제 1장을 직접 고르세요.`,
    chooseSecret: (name: string) => `${name} 차례입니다. 남은 비밀 의제 중 하나를 고르세요.`,
    choiceDone: "선택 완료. 다른 가문의 차례에는 남은 의제가 보이지 않습니다.",
    waitingTurn: (self: string, turn: string) =>
      `${self} 대기 중. 지금은 ${turn} 차례이며 남은 의제가 보이지 않습니다.`,
    voteSavedOk: "투표를 저장했습니다.",
    voteSavedFail: "투표를 저장하지 못했습니다.",
    applyOk: "투표 집계를 기록했습니다.",
    applyFail: "투표 집계를 기록하지 못했습니다.",
    voteSummaryOutcome: (label: string) => `${label} 선택됨`,
    votePhaseProgress: "투표 진행",
    votePhaseComplete: "투표 완료",
    tallyLine: (aye: number, nay: number, pass: number) => `찬성 ${aye} · 반대 ${nay} · 기권 ${pass}`,
    allHouseVotedLine: "참여 중인 모든 가문이 투표했습니다.",
    turnOnly: (name: string) => `${name} 차례`,
    voteCountLine: (done: number, total: number) => `${done}/${total || 0} 투표`,
    voteRoleGridAria: "투표 역할과 선두",
    leaderShort: "리더",
    moderatorShort: "중재자",
    ayeLead: "찬성 선두",
    nayLead: "반대 선두",
    advantageNow: "현재 우세",
    waitYourTurn: "내 차례가 오면 투표 선택지가 표시됩니다.",
    voteOptionsAria: "딜레마투표 선택",
    stepperMinusAria: "권력 토큰 줄이기",
    stepperPlusAria: "권력 토큰 늘리기",
    wagerOutputAria: "투표에 거는 권력 토큰",
    applyHint: "찬성/반대 권력 합계를 확인하고 결과를 직접 선택하세요.",
    saveVote: "투표 저장",
    applyTally: "집계 기록",
    labelAye: "찬성",
    labelNay: "반대",
    labelPass: "기권",
  },

};

export type Ko = typeof ko;
